In [1]:
import numpy as np

In [3]:
new_array = np.random.randint(1, 100, 20)
new_array

array([63, 11, 30, 91, 88,  6, 35, 94, 10, 54, 23, 31, 88, 51, 19, 90, 48,
       92, 74, 37])

In [5]:
new_array[new_array > 20]


array([63, 30, 91, 88, 35, 94, 54, 23, 31, 88, 51, 90, 48, 92, 74, 37])

In [6]:
new_array[new_array <= 20]

array([11,  6, 10, 19])

In [8]:
random_array = np.random.random((6, 1))
random_array

array([[0.62118673],
       [0.48972504],
       [0.57847369],
       [0.51907043],
       [0.37388571],
       [0.13920289]])

In [9]:
random_array.reshape(3, 2)

array([[0.62118673, 0.48972504],
       [0.57847369, 0.51907043],
       [0.37388571, 0.13920289]])

In [10]:
import pandas as pd

In [13]:
grades = {"Atil": 50, "Berk": 60, "Cem": 70, "Deniz": 80, "Ege": 90}
pd.Series(grades)

Atil     50
Berk     60
Cem      70
Deniz    80
Ege      90
dtype: int64

In [14]:
pd.Series(grades)

Atil     50
Berk     60
Cem      70
Deniz    80
Ege      90
dtype: int64

In [16]:
np_array = np.array([50, 56, 98])

In [18]:
pd.Series(np_array)

0    50
1    56
2    98
dtype: int32

In [20]:
data = np.random.randn(4,3)
data

array([[ 0.17535671, -0.09225682,  0.73366534],
       [-0.49626155, -0.50304769,  1.27917663],
       [ 0.57195674, -0.81531633, -1.53582434],
       [ 0.50524955, -1.58530935,  0.00306629]])

In [21]:
data_frame = pd.DataFrame(data)
data_frame


0         1         2
0  0.175357 -0.092257  0.733665
1 -0.496262 -0.503048  1.279177
2  0.571957 -0.815316 -1.535824
3  0.505250 -1.585309  0.003066